# Generated by Django 5.1.2 on 2024-10-22 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('text', 'Text')], max_length=10)),
                ('file_path', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('required_file_types', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_content', models.TextField()),
                ('files', models.ManyToManyField(related_name='reports', to='reports.file')),
                ('report_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reportform')),
            ],
        ),
    ]
